import { internalMutation } from "./_generated/server";

/**
 * Seed the 9 MotionKit presets (Phase A + Phase B) into the marketplace.
 * Run via: npx convex run motionkitSeed:seed
 * Safe to re-run — skips presets that already exist by name.
 */
export const seed = internalMutation({
  args: {},
  handler: async (ctx) => {
    const existing = await ctx.db.query("presets").collect();
    const existingNames = new Set(existing.map((p) => p.name));

    const presets = [
      // ─── Phase A: Validation Batch ────────────────────────────
      {
        name: "Lower Third",
        description:
          "Broadcast-style name + role identifier with sliding accent bar, scaling backing plate, and staggered text reveal.",
        category: "lower-third" as const,
        tags: ["lower-third", "name", "broadcast", "interview"],
        author: "MotionKit",
        bundleUrl: "local://presets/LowerThird",
        fps: 30,
        width: 1920,
        height: 1080,
        durationInFrames: 150,
        inputSchema: JSON.stringify({
          name: { type: "text", label: "Name", default: "Jane Doe", group: "Content" },
          role: { type: "text", label: "Role / Title", default: "Founder & CEO", group: "Content" },
          position: { type: "select", label: "Position", default: "bottom", options: ["bottom", "top"], group: "Layout" },
          fontSize: { type: "number", label: "Name Size", default: 56, min: 28, max: 120, step: 2, group: "Typography" },
          accentColor: { type: "color", label: "Accent Bar", default: "#f59e0b", group: "Colors" },
          textColor: { type: "color", label: "Text Color", default: "#ffffff", group: "Colors" },
          barColor: { type: "color", label: "Plate Color", default: "#0a0a0a", group: "Colors" },
        }),
        isPublic: true,
        status: "published" as const,
        downloads: 0,
        rating: 0,
      },
      {
        name: "Number Counter",
        description:
          "Animated count-up with prefix/suffix, decimals, and thousands separator. Perfect for stats, metrics, and revenue reveals.",
        category: "chart" as const,
        tags: ["number", "counter", "stat", "kpi", "metric"],
        author: "MotionKit",
        bundleUrl: "local://presets/NumberCounter",
        fps: 30,
        width: 1920,
        height: 1080,
        durationInFrames: 120,
        inputSchema: JSON.stringify({
          startValue: { type: "number", label: "Start Value", default: 0, min: 0, max: 1000000, step: 1, group: "Content" },
          endValue: { type: "number", label: "End Value", default: 12500, min: 0, max: 10000000, step: 1, group: "Content" },
          prefix: { type: "text", label: "Prefix", default: "$", group: "Content" },
          suffix: { type: "text", label: "Suffix", default: "", group: "Content" },
          decimals: { type: "number", label: "Decimal Places", default: 0, min: 0, max: 4, step: 1, group: "Content" },
          thousandsSeparator: { type: "toggle", label: "Thousands Separator", default: true, group: "Content" },
          label: { type: "text", label: "Caption", default: "Revenue Generated", group: "Content" },
          showLabel: { type: "toggle", label: "Show Caption", default: true, group: "Content" },
          countDuration: { type: "number", label: "Count Duration (sec)", default: 2.0, min: 0.5, max: 6, step: 0.1, group: "Animation" },
          fontSize: { type: "number", label: "Number Size", default: 220, min: 80, max: 360, step: 4, group: "Typography" },
          numberColor: { type: "color", label: "Number Color", default: "#f59e0b", group: "Colors" },
          labelColor: { type: "color", label: "Caption Color", default: "#a1a1aa", group: "Colors" },
          backgroundColor: { type: "color", label: "Background", default: "#09090b", group: "Colors" },
        }),
        isPublic: true,
        status: "published" as const,
        downloads: 0,
        rating: 0,
      },
      {
        name: "Bar Chart",
        description:
          "Animated horizontal bar chart with staggered reveal and counting values. Up to 5 bars — leave label empty to hide.",
        category: "chart" as const,
        tags: ["chart", "bar", "data", "comparison", "stats"],
        author: "MotionKit",
        bundleUrl: "local://presets/BarChart",
        fps: 30,
        width: 1920,
        height: 1080,
        durationInFrames: 180,
        inputSchema: JSON.stringify({
          title: { type: "text", label: "Chart Title", default: "Q4 Revenue by Region", group: "Header" },
          showTitle: { type: "toggle", label: "Show Title", default: true, group: "Header" },
          bar1Label: { type: "text", label: "Bar 1 Label", default: "North America", group: "Data" },
          bar1Value: { type: "number", label: "Bar 1 Value", default: 4200, min: 0, max: 1000000, step: 1, group: "Data" },
          bar2Label: { type: "text", label: "Bar 2 Label", default: "Europe", group: "Data" },
          bar2Value: { type: "number", label: "Bar 2 Value", default: 3100, min: 0, max: 1000000, step: 1, group: "Data" },
          bar3Label: { type: "text", label: "Bar 3 Label", default: "Asia Pacific", group: "Data" },
          bar3Value: { type: "number", label: "Bar 3 Value", default: 2800, min: 0, max: 1000000, step: 1, group: "Data" },
          bar4Label: { type: "text", label: "Bar 4 Label", default: "Latin America", group: "Data" },
          bar4Value: { type: "number", label: "Bar 4 Value", default: 1500, min: 0, max: 1000000, step: 1, group: "Data" },
          bar5Label: { type: "text", label: "Bar 5 Label", default: "", group: "Data" },
          bar5Value: { type: "number", label: "Bar 5 Value", default: 0, min: 0, max: 1000000, step: 1, group: "Data" },
          valueSuffix: { type: "text", label: "Value Suffix", default: "", group: "Data" },
          showValues: { type: "toggle", label: "Show Values", default: true, group: "Data" },
          barColor: { type: "color", label: "Bar Fill", default: "#f59e0b", group: "Colors" },
          trackColor: { type: "color", label: "Track", default: "#27272a", group: "Colors" },
          textColor: { type: "color", label: "Label Color", default: "#fafafa", group: "Colors" },
          titleColor: { type: "color", label: "Title Color", default: "#ffffff", group: "Colors" },
          backgroundColor: { type: "color", label: "Background", default: "#09090b", group: "Colors" },
        }),
        isPublic: true,
        status: "published" as const,
        downloads: 0,
        rating: 0,
      },

      // ─── Phase B: Visual-Impact Batch ─────────────────────────
      {
        name: "Aurora Background",
        description:
          "Slow-drifting mesh gradient with organic blob motion. Use as a backdrop for titles, lower-thirds, or product reveals.",
        category: "full" as const,
        tags: ["background", "gradient", "ambient", "loop", "aurora"],
        author: "MotionKit",
        bundleUrl: "local://presets/AuroraBackground",
        fps: 30,
        width: 1920,
        height: 1080,
        durationInFrames: 300,
        inputSchema: JSON.stringify({
          color1: { type: "color", label: "Color 1", default: "#7c3aed", group: "Palette" },
          color2: { type: "color", label: "Color 2", default: "#ec4899", group: "Palette" },
          color3: { type: "color", label: "Color 3", default: "#06b6d4", group: "Palette" },
          color4: { type: "color", label: "Color 4", default: "#f59e0b", group: "Palette" },
          baseColor: { type: "color", label: "Base / Background", default: "#0a0118", group: "Palette" },
          intensity: { type: "number", label: "Color Intensity", default: 0.7, min: 0.1, max: 1, step: 0.05, group: "Look" },
          blur: { type: "number", label: "Blur Amount", default: 90, min: 20, max: 200, step: 5, group: "Look" },
          speed: { type: "number", label: "Motion Speed", default: 1, min: 0.2, max: 3, step: 0.1, group: "Animation" },
          showGrain: { type: "toggle", label: "Film Grain", default: true, group: "Look" },
        }),
        isPublic: true,
        status: "published" as const,
        downloads: 0,
        rating: 0,
      },
      {
        name: "Particle Field",
        description:
          "Drifting glowing particles with optional constellation lines. Tech / AI / sci-fi backdrop for titles and reveals.",
        category: "full" as const,
        tags: ["background", "particles", "tech", "ambient", "loop"],
        author: "MotionKit",
        bundleUrl: "local://presets/ParticleField",
        fps: 30,
        width: 1920,
        height: 1080,
        durationInFrames: 300,
        inputSchema: JSON.stringify({
          count: { type: "number", label: "Particle Count", default: 80, min: 20, max: 200, step: 5, group: "Particles" },
          minSize: { type: "number", label: "Min Size", default: 2, min: 1, max: 12, step: 0.5, group: "Particles" },
          maxSize: { type: "number", label: "Max Size", default: 6, min: 2, max: 20, step: 0.5, group: "Particles" },
          speed: { type: "number", label: "Drift Speed", default: 1, min: 0.1, max: 3, step: 0.1, group: "Animation" },
          glowAmount: { type: "number", label: "Glow Amount", default: 12, min: 0, max: 40, step: 1, group: "Look" },
          particleColor: { type: "color", label: "Particle Color", default: "#fafafa", group: "Colors" },
          glowColor: { type: "color", label: "Glow Color", default: "#a78bfa", group: "Colors" },
          backgroundColor: { type: "color", label: "Background", default: "#0a0118", group: "Colors" },
          showConnections: { type: "toggle", label: "Constellation Lines", default: true, group: "Look" },
          connectionDistance: { type: "number", label: "Line Distance", default: 180, min: 60, max: 400, step: 10, group: "Look" },
        }),
        isPublic: true,
        status: "published" as const,
        downloads: 0,
        rating: 0,
      },
      {
        name: "Kinetic Typography",
        description:
          "Big, bold words slam onto screen one after another with blur, scale, and color punch. High-energy intros, hype reels, brand statements.",
        category: "intro" as const,
        tags: ["text", "kinetic", "bold", "intro", "hype"],
        author: "MotionKit",
        bundleUrl: "local://presets/KineticTypography",
        fps: 30,
        width: 1920,
        height: 1080,
        durationInFrames: 180,
        inputSchema: JSON.stringify({
          word1: { type: "text", label: "Word 1", default: "Bold", group: "Words" },
          word2: { type: "text", label: "Word 2", default: "Loud", group: "Words" },
          word3: { type: "text", label: "Word 3", default: "Unmissable", group: "Words" },
          word4: { type: "text", label: "Word 4", default: "Motion", group: "Words" },
          word5: { type: "text", label: "Word 5", default: "", group: "Words" },
          accentEvery: { type: "number", label: "Accent Every Nth Word", default: 3, min: 1, max: 5, step: 1, group: "Style" },
          fontSize: { type: "number", label: "Font Size", default: 240, min: 120, max: 400, step: 10, group: "Typography" },
          textColor: { type: "color", label: "Text Color", default: "#fafafa", group: "Colors" },
          accentColor: { type: "color", label: "Accent Color", default: "#f59e0b", group: "Colors" },
          backgroundColor: { type: "color", label: "Background", default: "#09090b", group: "Colors" },
          pulseBackground: { type: "toggle", label: "Background Pulse", default: true, group: "Style" },
        }),
        isPublic: true,
        status: "published" as const,
        downloads: 0,
        rating: 0,
      },
      {
        name: "Glitch Text",
        description:
          "RGB-split chromatic aberration text with periodic slice glitches and scanlines. Cyberpunk / tech / hacker aesthetic.",
        category: "title" as const,
        tags: ["glitch", "cyberpunk", "tech", "title", "vhs"],
        author: "MotionKit",
        bundleUrl: "local://presets/GlitchText",
        fps: 30,
        width: 1920,
        height: 1080,
        durationInFrames: 150,
        inputSchema: JSON.stringify({
          text: { type: "text", label: "Main Text", default: "SYSTEM ERROR", group: "Content" },
          subText: { type: "text", label: "Sub Text", default: "0xC0FFEE — RECONNECTING", group: "Content" },
          showSub: { type: "toggle", label: "Show Sub Text", default: true, group: "Content" },
          fontSize: { type: "number", label: "Font Size", default: 160, min: 60, max: 320, step: 4, group: "Typography" },
          glitchIntensity: { type: "number", label: "Glitch Intensity", default: 1, min: 0, max: 3, step: 0.1, group: "Effect" },
          glitchFrequency: { type: "number", label: "Glitch Frequency (per sec)", default: 4, min: 1, max: 15, step: 0.5, group: "Effect" },
          showScanlines: { type: "toggle", label: "CRT Scanlines", default: true, group: "Effect" },
          textColor: { type: "color", label: "Main Text", default: "#fafafa", group: "Colors" },
          redChannel: { type: "color", label: "Red Channel", default: "#ff0044", group: "Colors" },
          cyanChannel: { type: "color", label: "Cyan Channel", default: "#00f0ff", group: "Colors" },
          backgroundColor: { type: "color", label: "Background", default: "#000000", group: "Colors" },
        }),
        isPublic: true,
        status: "published" as const,
        downloads: 0,
        rating: 0,
      },
      {
        name: "Marquee Banner",
        description:
          "Multi-row scrolling text banner with alternating directions and rotation. Promo, hype, fashion-week energy.",
        category: "full" as const,
        tags: ["marquee", "scrolling", "promo", "banner", "hype"],
        author: "MotionKit",
        bundleUrl: "local://presets/MarqueeBanner",
        fps: 30,
        width: 1920,
        height: 1080,
        durationInFrames: 240,
        inputSchema: JSON.stringify({
          row1Text: { type: "text", label: "Row 1", default: "Now Booking — Q3 2026", group: "Content" },
          row2Text: { type: "text", label: "Row 2", default: "Limited Spots Available", group: "Content" },
          row3Text: { type: "text", label: "Row 3", default: "Apply Now", group: "Content" },
          separator: { type: "text", label: "Separator", default: "★", group: "Content" },
          speed: { type: "number", label: "Scroll Speed", default: 1, min: 0.2, max: 4, step: 0.1, group: "Animation" },
          rotation: { type: "number", label: "Rotation (deg)", default: -6, min: -45, max: 45, step: 1, group: "Layout" },
          fontSize: { type: "number", label: "Font Size", default: 110, min: 40, max: 240, step: 4, group: "Typography" },
          primaryColor: { type: "color", label: "Primary Color", default: "#fafafa", group: "Colors" },
          accentColor: { type: "color", label: "Accent Color", default: "#f59e0b", group: "Colors" },
          backgroundColor: { type: "color", label: "Background", default: "#09090b", group: "Colors" },
          fadeEdges: { type: "toggle", label: "Fade Edges", default: true, group: "Look" },
        }),
        isPublic: true,
        status: "published" as const,
        downloads: 0,
        rating: 0,
      },
      {
        name: "Shimmer Title",
        description:
          "Title with a continuous metallic shimmer sweeping across the text. Luxury, premium, and brand reveal energy.",
        category: "title" as const,
        tags: ["title", "shimmer", "luxury", "premium", "metallic"],
        author: "MotionKit",
        bundleUrl: "local://presets/ShimmerTitle",
        fps: 30,
        width: 1920,
        height: 1080,
        durationInFrames: 180,
        inputSchema: JSON.stringify({
          title: { type: "text", label: "Title", default: "Premium Quality", group: "Content" },
          subtitle: { type: "text", label: "Subtitle", default: "Crafted with care", group: "Content" },
          showSub: { type: "toggle", label: "Show Subtitle", default: true, group: "Content" },
          fontSize: { type: "number", label: "Font Size", default: 160, min: 60, max: 320, step: 4, group: "Typography" },
          shimmerSpeed: { type: "number", label: "Shimmer Speed", default: 1, min: 0.2, max: 3, step: 0.1, group: "Animation" },
          shimmerWidth: { type: "number", label: "Shimmer Width", default: 30, min: 10, max: 80, step: 2, group: "Animation" },
          showUnderline: { type: "toggle", label: "Show Underline", default: true, group: "Style" },
          baseColor: { type: "color", label: "Base Color", default: "#52525b", group: "Colors" },
          shimmerColor: { type: "color", label: "Shimmer Color", default: "#fafafa", group: "Colors" },
          subColor: { type: "color", label: "Subtitle Color", default: "#a1a1aa", group: "Colors" },
          backgroundColor: { type: "color", label: "Background", default: "#09090b", group: "Colors" },
        }),
        isPublic: true,
        status: "published" as const,
        downloads: 0,
        rating: 0,
      },
    ];

    const inserted: string[] = [];
    const skipped: string[] = [];

    for (const preset of presets) {
      if (existingNames.has(preset.name)) {
        skipped.push(preset.name);
        continue;
      }
      await ctx.db.insert("presets", preset);
      inserted.push(preset.name);
    }

    return { inserted, skipped };
  },
});
